#' Plot a Random Artpiece Generated by `make_markov_art` function
#'
#' @param data a matrix generated by `make_markov_art`
#' @param colour a colour pallet to use for plotting
#' @param save should plot be saved to disc?
#'
#' @return a plot generated by `image`
#' @export
#'
#' @examples
#' raw_data <- make_markov_art(size = 10, asp = 1, seed = 42)
#' plot_markov_art(data = raw_data, colour = viridisLite::mako(9999), save = FALSE)
plot_markov_art <- function(
    data,
    colour = viridisLite::mako(9999),
    save = FALSE){
  asp <- nrow(data) / ncol(data)
  if (save == TRUE) {
    png(filename = paste("beatifull_markov_art", Sys.time(), ".png", sep = ""))
    #    pdf(file = paste("beatifull_markov_art", Sys.time(), ".pdf", sep = ""))
    image(t(data)[, nrow(data):1],
          col = colour,
          axes = FALSE, xlab = "", ylab = "", main = "", asp = asp)
    dev.off()
  } else {
    image(t(data)[, nrow(data):1],
          col = colour,
          axes = FALSE, xlab = "", ylab = "", main = "", asp = asp)
  }
}
